feat(*): added checkbox comp, unit test, sb documentation
GovTechSG/sgds-web-component pull request #6
Opened 2022-10-05 08:32 UTC by haphizi

2022-10-10 04:30 UTC, clukhei requested changes

2022-10-10 04:30 UTC, clukhei commented on src/Checkbox/sgds-checkbox.scss
> +@import "~@govtechsg/sgds/sass/forms";
since this is a checkbox component only , can reduce the code imported by using @import `"~@govtechsg/sgds/sass/forms/form-check";` instead

2022-10-10 04:30 UTC, clukhei commented on src/Checkbox/sgds-checkbox.ts
> +      <label part="base" class="form-check">
why is the wrapper a label tag?

2022-10-10 04:30 UTC, clukhei commented on src/Checkbox/sgds-checkbox.ts
> +  @watch("checked", { waitUntilFirstUpdate: true })
reactive props like "checked" will trigger Lit's render function whenever its value change. So dont have to watch "checked" on render function if not render function will run twice when checked changes. I think watch is more for custom functions that is not part of Lit's native lifecycle

2022-10-10 04:30 UTC, clukhei commented on src/Checkbox/sgds-checkbox.ts
> +    this.checked = !this.checked;
somehow trying to get the e.target.value using @click event will return two values (initial and latest). I think click event runs twice ( the native click event and the custom handleClick() ) 

Dispatch a change event (lets say called "sgds-change"),  when this.emit('sgds-change') event changes. Either below line 37 
```this.emit('sgds-change')```

or 

create a function that uses @watch to watch checked and runs the emit method 

```
 @watch('checked', { waitUntilFirstUpdate: true })
  emitOnChange() {
   this.emit('sgds-change')
   }
```

and document this event name on storybook argstable under Event category

2022-10-11 02:44 UTC, haphizi commented on src/Checkbox/sgds-checkbox.ts
> +      <label part="base" class="form-check">
it is so that i don't need to label each input with id and for attribute to make it checkable

2022-10-24 00:23 UTC, rav3 commented
> _ No description provided. _
Fixed conflict
Updated inputId to checkboxId

2022-10-24 00:23 UTC, rav3 approved these changes

2022-10-24 00:23 UTC, rav3 commented on src/Checkbox/sgds-checkbox.ts
> +    this.checked = !this.checked;
we can add in the dispatch event here to check for changes
```suggestion
    this.checked = !this.checked;
    this.emit('sgds-change', {detail : {
      checked: this.checked
    }});
```

2022-10-27 11:55 UTC, clukhei approved these changes

2022-10-28 01:00 UTC, merged